# Generated by Django 5.1.3 on 2024-11-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('BLACK', 'BLACK'), ('GOLD', 'GOLD'), ('CLASSIC', 'CLASSIC')], default='CLASSIC', max_length=15),
        ),
    ]
