# Generated by Django 5.1.3 on 2024-11-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_prestamos',
            name='nombre',
            field=models.CharField(choices=[('HIPOTECARIO', 'HIPOTECARIO'), ('PERSONAL', 'PERSONAL'), ('PRENDARIO', 'HIPOTECARIO')], max_length=50),
        ),
    ]
