# Generated by Django 5.1.3 on 2024-11-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_alter_tipo_prestamos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='tipo',
            field=models.CharField(choices=[('HIPOTECARIO', 'HIPOTECARIO'), ('PRENDARIO', 'PRENDARIO'), ('PERSONAL', 'PERSONAL')], max_length=50),
        ),
        migrations.RenameField(
            model_name='prestamos',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.AddField(
            model_name='prestamos',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Tipo_prestamos',
        ),
    ]
