# Generated by Django 5.1.3 on 2024-11-25 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_alter_prestamos_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
