# Generated by Django 5.1.3 on 2024-11-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_alter_prestamos_fecha'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prestamos',
            table='prestamo',
        ),
    ]
