# Generated by Django 5.1.3 on 2024-11-25 00:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcatarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16, unique=True)),
                ('cvv', models.CharField(max_length=3)),
                ('fecha_venc', models.DateField(default=django.utils.timezone.now)),
                ('fecha_emicion', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('Debito', 'Debito'), ('Credito', 'Credito')], max_length=10)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarjetas.marcatarjeta')),
            ],
            options={
                'db_table': 'tarjeta',
            },
        ),
    ]
