# Generated by Django 5.1.3 on 2024-11-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0003_rename_cliente_id_tarjeta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcatarjeta',
            name='nombre',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'MasterCard')], max_length=50),
        ),
    ]
