# Generated by Django 5.1.3 on 2024-11-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0004_alter_marcatarjeta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='marca',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'MasterCard')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Marcatarjeta',
        ),
    ]
