# Generated by Django 5.1.3 on 2024-11-30 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0005_alter_tarjeta_marca_delete_marcatarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_venc',
            field=models.DateField(default=datetime.datetime(2025, 11, 30, 3, 45, 12, 855310, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo',
            field=models.CharField(choices=[('DEBITO', 'Debito'), ('CREDITO', 'Credito')], max_length=10),
        ),
    ]
