# Generated by Django 5.1.3 on 2024-12-03 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0006_alter_tarjeta_fecha_venc_alter_tarjeta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_venc',
            field=models.DateField(default=datetime.datetime(2025, 12, 3, 20, 21, 14, 892562, tzinfo=datetime.timezone.utc)),
        ),
    ]
