# Generated by Django 5.1.3 on 2024-11-25 00:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo_operacion', models.CharField(max_length=50)),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'movimientos',
            },
        ),
    ]
